#  未来配置文件有两个维度  6种写法    （用springboot不是一定要用springcloud   用springcloud基本都会用springboot）
# 1.application.xxx---springboot默认提供的（只要是springboot应用）
# 2.bootstrap.xxx---springcloud提供的（只要引入cloud的某些组件）
#bootstrap的优先级会高于application优先级  bootstrap.properties application.properties
# xxx有三种形式：properties(优先级最高)  yaml   yml


#  application中主要配置应用需要的各个组件的信息（MySQL  Redis   MQ...）

server:
  port: 8501   # user微服务的端口


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource   # 数据源连接池（最快）
    driver-class-name: com.mysql.jdbc.Driver   # 指定数据库的驱动
    url: jdbc:mysql://192.168.76.15:3306/tingshu_user
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true   # 这种写法会有风险











