# web port
server.port=9001
# no web
#spring.main.web-environment=false
# log config
logging.config=classpath:logback.xml
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
### 指定调度器地址
xxl.job.admin.addresses=http://127.0.0.1:8888/xxl-job-admin
### xxl-job, access token（执行器会被调度器通信访问token）
xxl.job.accessToken=default_token
### xxl-job executor appname
# (执行器名字可理解应用注册到Nacos注册中心的名字，多个执行器名字要是唯一的) 为空则关闭自动注册，则需要程序员手动指定执行器的地址信息，供调度中心使用
# 推荐指定上名字 （如果指定名字 调度中心则通过底层注册表可以动态发现执行器机器地址）
xxl.job.executor.appname=xxl-job-executor-hello
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
#（执行器地址 可手动指定以及默认获取）
# http://192.168.200.1:9999
xxl.job.executor.address=
### xxl-job executor server-info
#（执行器服务信息【ip和端口】）
xxl.job.executor.ip=
xxl.job.executor.port=9999
### xxl-job executor log-path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays=30
